severity: low
exclude:
  - message: Codacy project public id
    pattern: f5f5ce45a1594391abde33a206f53d84

  - message: Sourcemaps
    pattern: sourceMappingURL=data:application/json;base64,

  - message: Giphy links
    pattern: https://media.giphy.com/media/

  - message: Dependencies
    paths:
      - package-lock.json
      - node_modules
      - venv
      - yarn-error.log
      - yarn.lock
